  Clockwork is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clockwork is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Clockwork.  If not, see <http://www.gnu.org/licenses/>.


=head1 NAME

cw-help - Clockwork Help System

=head1 SYNOPSIS

B<cw-help> -c

B<cw-help> -g

B<cw-help> TOPIC

=head1 DESCRIPTION

#INTRO

B<cw-help> is the Clockwork help system.

=head1 OPTIONS

=over

=item B<-c>, B<--commands>

Show the available standard commands, and a summary of what they do.

=item B<-g>, B<--guides>

List long-form documentation, howtos and guides that ar distributed with
Clockwork.

=back

=head1 AUTHOR

#AUTHOR

=cut
