  Clockwork is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Clockwork is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Clockwork.  If not, see <http://www.gnu.org/licenses/>.


=head1 NAME

cw-localsys - Clockwork Agent System Tool

=head1 SYNOPSIS

B<cw-localsys> I<ACTION> [args ...]

=head1 DESCRIPTION

B<Clockwork> is a configuration management system designed to
securely and correctly enforce configuration policies on lots of
hosts.

It can ensure that files have the right attributes (owner,
group, permissions, etc.) and content.  It can maintain a specific
set of installed packages, and even make sure that system user
accounts exist.

B<cw-localsys> is a utility script that is utilized by B<cogd> to
handle platform-specific things like package installations and
service management.  It inspects the system environment to determine
the correct tools to use to (for example) restart services or install
pacakges.

=head1 INFORMATIONAL ACTIONS

=over

=item B<identify>

Autodetect the local system type, and then print that information.

=back

=head1 SERVICE ACTIONS

=over

=item B<svc-run-status> I<SERVICE>

Determine whether or not the service is running (per LSB semantics).

An exit code of B<0> indicates that the service is running.  Any
other value indicates either that the service is stopped, or that
the init script had other issues (dead locsk, missing PID file, etc.)

=item B<svc-boot-status> I<SERVICE>

Determine whether or not the service is configured to start at boot,
on the current runlevel.

An exit code of B<0> indicates that the service will start at
boot.  Any other value indicates otherwise.

=item B<svc-init> I<SERVICE> I<VERB>

Run the services init script, using I<VERB> as the action (i.e.
start, stop, reload, etc.).

Exits B<0> if the action succeeded, or non-zero if it failed.

=item B<svc-enable> I<SERVICE>

Set the service to start on boot.

Exits B<0> on success, or non-zero if it failed.

=item B<svc-disable> I<SERVICE>

Prevent the service from starting on boot.

Exits B<0> on success, or non-zero if it failed.

=back

=head1 PACKAGE ACTIONS

=over

=item B<pkg-version> I<PACKAGE>

Prints out the installed version of the named package.

Exits B<0> if the package is in fact installed.  Otherwise,
exits non-zero, and nothing will be printed.

=item B<pkg-latest> I<PACKAGE>

Query upstream repositories (APT, YUM, etc.) to determine the
latest available version of the named package.

Exits B<0> if the package is available upstream.  In this case,
the latest candidate version is printed to standard output.
Otherwise, exits non-zero to indicate that the package is not
available for installation.

=item B<pkg-version> I<PACKAGE> I<VERSION>

Install the package at the given version.  If I<VERSION> is
the string "latest", the latest available version will be
installed.

An exit code of B<0> indicates that the install succeeded.

=item B<pkg-remove> I<PACKAGE>

Uninstall the named package.

Exits B<0> on success.

=back

=head1 EXIT CODE

For known actions on known platforms, exit codes depend solely on
the action being executed.

Otherwise, cw-localsys exits:

=over

=item B<125>

An unknown action was specified.

=item B<126>

Unable to detect the local system type.

=back

=head1 SEE ALSO

#SEEALSO

=head1 AUTHOR

#AUTHOR

=cut
