\"
\"  Copyright 2011 James Hunt <james@jameshunt.us>
\"
\"  This file is part of Clockwork.
\"
\"  Clockwork is free software: you can redistribute it and/or modify
\"  it under the terms of the GNU General Public License as published by
\"  the Free Software Foundation, either version 3 of the License, or
\"  (at your option) any later version.
\"
\"  Clockwork is distributed in the hope that it will be useful,
\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
\"  GNU General Public License for more details.
\"
\"  You should have received a copy of the GNU General Public License
\"  along with Clockwork.  If not, see <http://www.gnu.org/licenses/>.
\"

.TH policyd.conf "5" "January 2011" "Clockwork" "Clockwork File Formats"
.SH NAME
policyd.conf \- Clockwork Policy Master configuration file
.br

.SH SYNOPSIS
.B /etc/clockwork/policyd.conf

.SH DESCRIPTION
\fBpolicyd\fR(1) reads its configuration from
.I /etc/clockwork/policyd.conf
(unless a different file is specified with the \-c option).
.PP

.SH DIRECTIVES
.PP
The following configuration directives are valid for \fIpolicyd.conf\fR.

\"----------------------------------------------------------------------
.SS ca_cert_file
.PP
Path to the Certificate Authority's certificate.
.PP
This certificate is used to validate the certificates of all clients
that connect to the policy master and attempt to retrieve configuration
policy.
.PP
This may seem a bit excessive, but the paranoia is aimed at a subtle
attack that attempts to expose information about other hosts in the
environment.  If the policy master doesn't validate certificates, a
malicious client could coerce the master into leaking information about
packages, user accounts, and other sensitive aspects of each system
under Clockwork's control.

\"----------------------------------------------------------------------
.SS crl_file
.PP
Path to a Certificate Revocation List
.PP
The certificate revocation list includes all certificates revoked by
\fIcwca revoke [fqdn]\fR, and allows the policy master to refuse service
to any client connecting with a revoked certificate.
.PP
The certificate revocation list includes all certificates revoked by
As an administrator, you may want to revoke a certificate in reaction
to a host being compromised or retired.  Revocation is also useful to
allow cwcert to obtain a new host certificate.

\"----------------------------------------------------------------------
.SS cert_file
.PP
Path to this Policy Master's certificate.
.PP
This certificate will be presented to all agents connectng to us,
so that they can verify our identity and ensure that they are not
receiving bogus policy definitions from a rogue element in the network.
.PP
This certificate \fBmust\fR be signed by the CA whose certificate is given
in the \fBca_cert_file\fR directive.  Clients will check this.

\"----------------------------------------------------------------------
.SS key_file
.PP
Path to this Policy Master's private key
.PP
The key file will be used to unlock the policy master's certificate
(see \fBcert_file\fR directive) in order to prove that it has the rights to
use that certificate.

\"----------------------------------------------------------------------
.SS requests_dir
.PP
Directory where policyd will store pending SSL Certificate Requests from
agents (via \fIcwcert\fR), and where \fIcwca\fR will look to sign / reject
them.

\"----------------------------------------------------------------------
.SS certs_dir
.PP
Directory where policyd will store signed SSL Certificates generated on
behalf of agents via \fIcwca\fR.

\"----------------------------------------------------------------------
.SS manifest_file
.PP
Path to the policy definitions.
.PP
The manifest contains all of the policy definitions, and what clients they
should be given to, for this Policy Master.

\"----------------------------------------------------------------------
.SS log_level
.PP
Set the logging threshold.  Valid values are:
.RS 4
.IP \fBnone\fR 1i
Suppress all logging.
.IP \fBcritical\fR
Fatal issues that cause immediate termination.
.IP \fBerror\fR
Non-fatal issues that prevent proper system operation.
.IP \fBwarning\fR
Minor problems that do not hinder system operation.
.IP \fBnotice\fR
Informational messages that assist in system diagnostics.
.IP \fBdebug\fR
Messages for chasing down bugs.
.IP \fBall\fR
Log everything (same as debug).
.RE
.PP
Each level includes all "more important" levels.  'alert'
will log emergency and alert messages.  'notice' is everything
but debugging messages, etc.
.PP
A good starting point is 'warning'; default is 'error'.

\"----------------------------------------------------------------------
.SS db_file
.PP
A SQLite database that the policyd will use to store agent information.
.PP
If this Policy Master is itself a client of another Policy Master (or
even itself), make sure that the path specified for \fBdb_file\fR is
not the same as the path used by the agent.

\"----------------------------------------------------------------------
.SS cache_dir
.PP
A directory that policyd will use to cache the list of facts that agents
provide it.

\"----------------------------------------------------------------------
.SH DEFAULTS
.PP
The following default values will be used unless they are overridden.
.PP
port          = 7890
.PP
manifest_file = "/etc/clockwork/manifest.pol"
.PP
ca_cert_file  = "/etc/clockwork/ssl/CA.pem"
.br
cert_file     = "/etc/clockwork/ssl/cert.pem"
.br
crl_file      = "/etc/clockwork/ssl/revoked.pem"
.br
key_file      = "/etc/clockwork/ssl/key.pem"
.PP
requests_dir  = "/etc/clockwork/ssl/pending"
.br
certs_dir     = "/etc/clockwork/ssl/signed"
.PP
log_level     = "error"
.PP
lock_file     = "/var/lock/subsys/policyd"
.br
pid_file      = "/var/run/policyd.pid"
.PP
db_file       = "/var/lib/clockwork/master.db"
.br
cache_dir     = "/var/cache/clockwork"
