\"
\"  Copyright 2011 James Hunt <james@jameshunt.us>
\"
\"  This file is part of Clockwork.
\"
\"  Clockwork is free software: you can redistribute it and/or modify
\"  it under the terms of the GNU General Public License as published by
\"  the Free Software Foundation, either version 3 of the License, or
\"  (at your option) any later version.
\"
\"  Clockwork is distributed in the hope that it will be useful,
\"  but WITHOUT ANY WARRANTY; without even the implied warranty of
\"  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
\"  GNU General Public License for more details.
\"
\"  You should have received a copy of the GNU General Public License
\"  along with Clockwork.  If not, see <http://www.gnu.org/licenses/>.
\"

.TH res_dir "5" "June 2011" "Clockwork" " Clockwork Resource Types"'"
\"----------------------------------------------------------------
.SH NAME
res_dir \- Clockwork Resource Type for system directories
.br

\"----------------------------------------------------------------
.SH DESCRIPTION
The \fBres_dir\fR resource gives administrators a way to manage
the presence of directories and the permissions on them.

\"----------------------------------------------------------------
.SH ATTRIBUTES

.B path
.RS 8
The path (from the client's point of view) to the directory to
be managed.
.RE
.PP

.B owner
.RS 8
The name or UID of the user who should own the directory.
.RE
.PP

.B group
.RS 8
The name or GID of the group who should own this directory.
.RE
.PP

.B mode
.RS 8
The permissions set for this directory.  THe value must be
specified in octal notation, i.e. 0750 for rwxr-x---.
.RE
.PP

\"----------------------------------------------------------------
.SH EXAMPLES

.SS Basic Usage
The following policy configuration would create /srv/www, and
make it readable, writable and traversable by the apache user
(for running Apache) and the web group (people who manage the
code and content of web sites).
.PP
.RS 4
.nf
directory "/srv/www" {
    owner: "apache"
    group: "web"
    mode:  "0775"
}
.fi
.RE
.PP


\"----------------------------------------------------------------
.SH CAVEATS

.SS 1. UID / GID Support
Even though the documentation above says that the \fBowner\fR and
\fBgroup\fR attributes can be set to either a name or an ID, the
system only works with names.  IDs will be ignored, as if the ID
was 0.
.PP

\"----------------------------------------------------------------
.SH DEPENDENCIES
Directory resources implicitly create the following dependencies:
.PP
.SS User Owner (owner)
If the
.B owner
attribute is specified, the directory resource will depend on the
existence of that user.  This is designed to ensure that directories
are owned by valid system users.
.PP

.SS Group Owner (group)
If the
.B group
attribute is specified, the directory resource will depend on the
existence of that group.  This is designed to ensure that directories
are owned by valid system groups.
.PP

.SS Parent Directories
Missing directories in between the directory path and the root (/)
will be created if necessary (for existant resources).
By default, these parent directories will be owned by root:root with
mode 0755.  However, if the policy defines other directory resources
with matching paths, they will be marked as dependencies.
.PP
An example should clear up any confusion:
.PP
.RS 4
.nf
dir "/u/apps" {
    owner: "webmaster"
    group: "web"
    mode:  0755
}

dir "/u/apps/test.example.net" {
    owner: "apache"
    group: "web"
    mode:  0775
}
.fi
.RE
.PP
If the above policy was enforced on a host without the /u directory,
the following would happen (in order):
.PP
.nr steps 1 1
.IP \n[steps]. 3
Create /u, per defaults (root:root; 0755)
.IP \n+[steps].
Create /u/apps, per policy (webmaster:web; 0755)
.IP \n+[steps].
Create /u/apps/test.example.net, per policy (apache:web; 0775)
.PP

\"----------------------------------------------------------------
.SH AUTHOR
Clockwork was conceived and written by James Hunt.
.PP
Original ideas were stolen from
.B CFEngine
(Mark Burgess) and
.B Puppet
(Luke Kanies).

\"----------------------------------------------------------------
.SH BUGS
None.
