#!/bin/bash

VG=/usr/bin/valgrind
EFAIL=61

if [[ ! -x $VG ]]; then
	echo "SKIP: $VG not found (Valgrind not installed or otherwise unavailable)";
	exit 77;
fi

SUPPS="t/tmp/clockwork.supp"
cat >$SUPPS <<EOF
{
   <libzmq3_socketcall_sendto>
   Memcheck:Param
   socketcall.sendto(msg)
   fun:send
   ...
}
{
   <libzmq3_socketcall_sendto>
   Memcheck:Param
   socketcall.send(msg)
   fun:send
   ...
}
EOF

TEMPFILE=$(mktemp);
trap "rm -f $TEMPFILE" INT TERM EXIT
$VG --tool=memcheck --leak-check=full --show-leak-kinds=all --error-exitcode=$EFAIL --suppressions=$SUPPS 2>$TEMPFILE >/dev/null -- "$@"
if [[ $? == $EFAIL ]]; then
	echo "FAIL: $@"
	cat >&2 $TEMPFILE
	exit 1
else
	echo "PASS: $@"
	exit 0
fi
