#!/bin/sh

#
# cwtool - Portable Bourne Shell Package/Service Manager
#
# author:  James Hunt <james@niftylogic.com>
# created: 2014-05-20
#

# USAGE: cwtool <action> [arguments]
#
# Supported actions:
#
#   identify
#
#   svc-run-status  <service>
#   svc-boot-status <service>
#   svc-init        <service> <action>
#   svc-enable      <service>
#   svc-disable SVC <service>
#
#   pkg-version <package>
#   pkg-latest  <package>
#   pkg-install <package> <version>
#   pkg-remove  <package>
#

export PATH=/sbin:/bin:/usr/sbin:/usr/bin

#################################################################
# AUTO-DETECTION
#

AUTO_PKG=undetermined
if test -x "/usr/bin/dpkg-query" \
&& test -x "/usr/bin/apt-get"; then
	AUTO_PKG=debian

elif test -x "/bin/rpm" \
  && test -x "/usr/bin/yum"; then
	AUTO_PKG=redhat
fi

AUTO_SVC=undetermined
if test -x "/usr/sbin/invoke-rc.d" \
&& test -x "/usr/sbin/update-rc.d"; then
	AUTO_SVC=debian

elif test -x "/sbin/chkconfig"; then
	AUTO_SVC=redhat
fi

#################################################################

ACTION=$1
test -z "$ACTION" || shift

test "x$SYSTYPE" = "x" && SYSTYPE="auto"
if [ "x$SYSTYPE" = "xauto" ]; then
	SYSTYPE=undetermined
	case $ACTION in
	pkg-*) SYSTYPE=$AUTO_PKG ;;
	svc-*) SYSTYPE=$AUTO_SVC ;;
	esac
fi

#################################################################

on_debian () {
	export DEBIAN_FRONTEND=noninteractive

	case $ACTION in
	pkg-version)
		NAME=$1
		out=$(/usr/bin/dpkg-query -W -f='${db:status-abbrev} ${Version}' "$NAME")
		rc=$?
		status=$(echo $out | cut -d " " -f1)
		version=$(echo $out | cut -d " " -f2)
		if [ "$status" = "rc" -o "$status" = "un" -o $rc -ne 0 ]; then
			exit 1 # treat as not installed
		elif [ "$status" = "ii" ]; then
			echo $version
			exit 0 # treat as installed
		else
			exit 2 # treat as broken
		fi
		;;
	pkg-latest)
		NAME=$1
		if test -x /usr/bin/apt-cache; then
			/usr/bin/apt-cache policy $NAME | grep Candidate | sed -e 's/[^:]*: *//' | tr -d '\n'
			exit $?
		fi
		exit 0
		;;
	pkg-install)
		NAME=$1
		VERSION=$2
		ARGS="-qq --assume-no -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold"
		if [ "x$VERSION" = "xlatest" ]; then
			/usr/bin/apt-get $ARGS install "$NAME"
			exit $?
		else
			# specific version
			echo "$VERSION" | grep -q '-' || VERSION="$VERSION-*"
			/usr/bin/apt-get $ARGS install "$NAME=$VERSION"
			exit $?
		fi
		;;
	pkg-remove)
		NAME=$1
		/usr/bin/dpkg --purge "$NAME"
		exit $?
		;;

	svc-run-status)
		NAME=$1
		/usr/sbin/service $NAME status
		RC=$?
		[ "x$RC" = "x7" ] && exit 1
		exit $RC
		;;
	svc-boot-status)
		NAME=$1
		/usr/sbin/invoke-rc.d --quiet --query "$NAME" start
		RC=$?
		[ "x$RC" = "x104" ] && exit 0
		exit $RC
		;;
	svc-init)
		NAME=$1
		VERB=$2
		if test "x$NAME" = "xcogd" && test "x$VERB" = "xrestart" && test "x$COGD" != "x"; then
			touch /var/lock/cogd/.needs-restart
		else
			/usr/sbin/service $NAME $VERB
		fi
		exit $?
		;;
	svc-enable)
		NAME=$1
		/usr/sbin/update-rc.d -f "$NAME" remove
		/usr/sbin/update-rc.d    "$NAME" defaults
		exit $?
		;;
	svc-disable)
		NAME=$1
		/usr/sbin/update-rc.d -f "$NAME" remove
		exit $?
		;;
	esac
}

#################################################################

on_redhat () {
	case $ACTION in
	pkg-version)
		NAME=$1
		/bin/rpm --qf='%{VERSION}' -q "$NAME" | /bin/grp -qv 'is not installed$'
		exit $?
		;;
	pkg-latest)
		NAME=$1
		/usr/bin/repoquery --qf '%{VERSION}' -q "$NAME"
		exit 0
		;;
	pkg-install)
		NAME=$1
		VERSION=$2
		if [ "x$VERSION" = "xlatest" ]; then
			/usr/bin/yum install -qy "$NAME"
			exit $?
		else
			# specific version
			/usr/bin/yum install -qy "$NAME-$VERSION"
			exit $?
		fi
		;;
	pkg-remove)
		NAME=$1
		/usr/bin/yum erase -qy "$NAME"
		;;

	svc-run-status)
		NAME=$1
		/usr/sbin/service $NAME status
		exit $?
		;;
	svc-boot-status)
		NAME=$1
		/sbin/chkconfig --list "$NAME" | /bin/grep -q ':on'
		exit $?
		;;
	svc-init)
		NAME=$1
		VERB=$2
		/usr/sbin/service $NAME $VERB
		exit $?
		;;
	svc-enable)
		NAME=$1
		/sbin/chkconfig "$NAME" on
		exit $?
		;;
	svc-disable)
		NAME=$1
		/sbin/chkconfig "$NAME" on
		exit $?
		;;
	esac
}

#################################################################

if [ "x$ACTION" = "xidentify" ]; then
	echo "$AUTO_SVC (services)"
	echo "$AUTO_PKG (packaging)"
	exit 0
fi

case $SYSTYPE in
debian)
	on_debian "$@"
	;;
redhat)
	on_redhat "$@"
	;;
*)
	# unknown flavor
	exit 126
	;;
esac

# unknown command, the on_* functions didn't exit
exit 125
