#!/usr/bin/perl
use strict;
use warnings;

my $prog = shift @ARGV or die "USAGE: $0 program.S\n";
my $ccov = "$prog.pcov";

-f $prog or die "$prog: $!\n";
-f $ccov or die "$ccov: $!\n";

open my $fh, "<", $ccov
	or die "$ccov: $!\n";
my (%counts, %ops);
while (<$fh>) {
	my ($addr, $op) = split /\s/;
	$counts{$addr}++;
	$ops{$addr} = $op;
}
close $fh;
use Data::Dumper;
print Dumper \%counts;

my @report;
open my $dism, "-|", "./pn -d $prog"
	or die "disassembly failed: $!\n";
while (<$dism>) {
	if (m/0x([0-9a-f]{8}): ([0-9a-f]{2})/ && $counts{$1}) {
		my ($addr, $op) = ($1, $2);
		die "binary image / ccov report mismatch detected;\n".
		    "opcode at 0x$addr is $op (ccov has $ops{$addr})\n"
			if $ops{$addr} ne $op;
		push @report, sprintf("%13i: %s", $counts{$addr}, $_);
	} else {
		push @report, sprintf("%14s %s", "", $_);
	}
}

print $_ for @report;
exit 0;
