#!/usr/bin/env ruby

#
# template-erb - Clockwork ERB Template Renderer
#
# author:  James Hunt <james@niftylogic.com>
# created: 2014-05-10
#

require 'erb'

class ClockworkERB
	def var n, v
		instance_variable_set "@#{n.gsub(/\./, '_')}", v
	end
end
inst = ERB.new(File.read(ARGV[0])).def_class(ClockworkERB, 'render()').new
while l = $stdin.gets do
	k, v = l.gsub(/\r?\n$/, '').split '=', 2
	inst.var k, v
end
$stdout.print inst.render

# vim:ft=ruby
