#!/bin/sh

#
# cw-pkg - Portable Bourne Shell Package Manager
#
# author:  James Hunt <james@jameshunt.us>
# created: 2014-01-24
#

# USAGE: cw-pkg <action> <name> [<version>]
#
# The following actions must be defined:
#
#   version PKG       Print out the installed version of
#                     the named package, on a single line.
#
#                       exit 0    = package is installed
#                       otherwise = package is not installed
#
#   latest PKG        Print out the latest available version
#                     of the named package, on a single line,
#                     and then exit 0.
#
#                       exit 0    = package is available
#                       otherwise = package is not available
#
#   install PKG       Install the named package.  If a version
#   install PKG VER   isn't given, the latest version will be
#                     installed.
#
#                       exit 0    = installed successfully
#                       otherwise = failure (any reason)
#
#   remove PKG        Uninstall the named package.
#
#                       exit 0    = removed successfully
#                       otherwise = failure (any reason)
#
# Any unrecognized commands should return exit code 125.
#

ACTION=$1
NAME=$2
VERSION=$3

case $ACTION in
version)
	/bin/rpm --qf='%{VERSION}' -q "$NAME" | /bin/grp -qv 'is not installed$'
	exit $?
	;;
latest)
	/usr/bin/repoquery --qf '%{VERSION}' -q "$NAME"
	exit $?
	;;
install)
	if [ -z $VERSION ]; then
		# no version
		/usr/bin/yum install -qy "$NAME"
		exit $?
	else
		# specific version
		/usr/bin/yum install -qy "$NAME-$VERSION"
		exit $?
	fi
	;;
remove)
	/usr/bin/yum erase -qy "$NAME"
	exit $?
	;;
esac
exit 126
