#!/bin/bash

case $1 in
pass)
	echo "pass mode activated"
	echo "exiting with RC=0"
	exit 0
	;;

fail)
	echo >&2 "FAIL mode activated"
	echo >&2 "(oh noes!)"
	echo "exiting with RC=1"
	exit 1
	;;

crash)
	kill -TERM $$
	exit 3
	;;

esac

echo "UNKNOWN MODE: $1"
exit 14;
