#!/bin/sh

#
# pkg - Test Package Manager
#
# author:  James Hunt <james@niftylogic.com>
# created: 2014-01-25
#

# USAGE: cw-pkg <action> <name> [<version>]

ACTION=$1
NAME=$2
VERSION=$3

case $NAME in
simple)
	case $ACTION in
	version) printf "1.2.3-4"; exit 0 ;;
	latest)  printf "1.3.7-1"; exit 0 ;;
	install) exit 0 ;; # success
	remove)  exit 0 ;; # success
	esac
	;;
multiline)
	case $ACTION in
	version) printf "1.2.3-4\nline2"; exit 0 ;;
	latest)  printf "1.3.7-1\nlineB"; exit 0 ;;
	install) exit 0 ;; # success
	remove)  exit 0 ;; # success
	esac
	;;
absent)
	case $ACTION in
	version) exit 1 ;;
	latest)  exit 1 ;;
	install) exit 1 ;;
	remove)  exit 1 ;;
	esac
	;;
esac
exit 126
