#!/bin/sh

#
# cw-pkg - Portable Bourne Shell Package Manager
#
# author:  James Hunt <james@niftylogic.com>
# created: 2014-01-24
#

# USAGE: cw-svc <action> <name>

ACTION=$1
NAME=$2

case $NAME in
running-service)
	case $ACTION in
	run-status)   exit 0 ;;
	boot-status)  exit 0 ;;
	start)        exit 1 ;;
	stop)         exit 0 ;;
	restart)      exit 0 ;;
	reload)       exit 0 ;;
	enable)       exit 0 ;;
	disable)      exit 0 ;;
	esac
	;;
stopped-service)
	case $ACTION in
	run-status)   exit 1 ;;
	boot-status)  exit 1 ;;
	start)        exit 0 ;;
	stop)         exit 1 ;;
	restart)      exit 0 ;;
	reload)       exit 1 ;;
	enable)       exit 0 ;;
	disable)      exit 0 ;;
	esac
	;;
bogus)
	case $ACTION in
	run-status)   exit 1 ;;
	boot-status)  exit 1 ;;
	start)        exit 1 ;;
	stop)         exit 1 ;;
	restart)      exit 1 ;;
	reload)       exit 1 ;;
	enable)       exit 1 ;;
	disable)      exit 1 ;;
	esac
	;;
esac
exit 125
