#!/bin/sh

#
# cw-pkg - Portable Bourne Shell Package Manager
#
# author:  James Hunt <james@jameshunt.us>
# created: 2014-01-24
#

# USAGE: cw-pkg <action> <name> [<version>]
#
# The following actions must be defined:
#
#   version PKG       Print out the installed version of
#                     the named package, on a single line.
#
#                       exit 0 = package is installed
#                       exit 1 = package is not installed
#                       exit 2 = package is in a error state (non-installed and non-removed)
#
#   latest PKG        Print out the latest available version
#                     of the named package, on a single line,
#                     and then exit 0.
#
#                       exit 0    = package is available
#                       otherwise = package is not available
#
#   install PKG       Install the named package.  If a version
#   install PKG VER   isn't given, the latest version will be
#                     installed.
#
#                       exit 0    = installed successfully
#                       otherwise = failure (any reason)
#
#   remove PKG        Uninstall the named package.
#
#                       exit 0    = removed successfully
#                       otherwise = failure (any reason)
#
# Any unrecognized commands should return exit code 125.
#

ACTION=$1
NAME=$2
VERSION=$3

export DEBIAN_FRONTEND=noninteractive

case $ACTION in
version)
	out=$(/usr/bin/dpkg-query -W -f='${db:status-abbrev} ${Version}' "$NAME")
	rc=$?
	status=$(echo $out | cut -d " " -f1)
	version=$(echo $out | cut -d " " -f2)
	if [ "$status" = "rc" -o "$status" = "un" -o $rc -ne 0 ]; then
		exit 1 # treat as not installed
	elif [ "$status" = "ii" ]; then
		echo $version
		exit 0 # treat as installed
	else
		exit 2 # treat as broken
	fi
	;;
latest)
	# FIXME: make this work under debian
	exit 0
	;;
install)
	if [ -z $VERSION ]; then
		# no version
		/usr/bin/apt-get install -qq --assume-no "$NAME"
		exit $?
	else
		# specific version
		echo "$VERSION" | grep -q '-' || VERSION="$VERSION-*"
		/usr/bin/apt-get install -qq --assume-no "$NAME=$VERSION"
		exit $?
	fi
	;;
remove)
	/usr/bin/apt-get purge -qq --assume-no "$NAME"
	exit $?
	;;
esac
exit 126
