#!/bin/sh

#
# cw-pkg - Portable Bourne Shell Package Manager
#
# author:  James Hunt <james@jameshunt.us>
# created: 2014-01-24
#

# USAGE: cw-svc <action> <name>
#
# The following actions must be defined:
#
#   run-status SVC    Determine whether or not the service is
#                     running (per LSB semantics).
#
#                       exit 0    = service is running
#                       otherwise = service is not running
#                                   or has other init-script
#                                   issues (dead locks, no
#                                   PID file, etc.)
#
#   boot-status SVC   Determine whether or not the service is
#                     set to be started on boot (runlevel 3)
#
#                       exit 0    = service starts at boot
#                       otherwise = service is off by default
#
#   start SVC         Start the (stopped) service
#
#                       exit 0    = service started successfully
#                       otherwise = failed to start
#
#   stop SVC          Stop the (running) service
#
#                       exit 0    = service stopped successfully
#                       otherwise = failed to stop
#
#   enable SVC        Set the service to start on boot (runevel 3)
#
#                       exit 0    = service enabled at boot
#                       otherwise = failure
#
#   disable SVC       Keep the service from starting at boot
#
#                       exit 0    = service won't start at boot
#                       otherwise = failure
#
# Any unrecognized commands should return exit code 125.
#

ACTION=$1
NAME=$2

case $ACTION in
run-status)
	/usr/sbin/service $NAME status 2>/dev/null >/dev/null
	RC=$?
	[ $RC = 7 ] && exit 1
	exit $RC
	;;
boot-status)
	/usr/sbin/invoke-rc.d --quiet --query "$NAME" start
	RC=$?
	[ $RC = 104 ] && exit 0
	exit $RC
	;;
start|stop|restart|reload)
	/usr/sbin/service $NAME $ACTION 2>/dev/null >/dev/null
	exit $?
	;;
enable)
	/usr/sbin/update-rc.d -f "$NAME" remove
	/usr/sbin/update-rc.d    "$NAME" defaults
	exit $?
	;;
disable)
	/usr/sbin/update-rc.d -f "$NAME" remove
	exit $?
	;;
esac
exit 125
