#!/bin/sh

#
# unspec/cw-svc - Portable Bourne Shell Service Manager
#  (unspecified, noop platform)
#
#
# author:  James Hunt <james@jameshunt.us>
# created: 2014-01-25
#

# This is a special handler used as a failsafe fallback when
# Clockwork can't figure out what service manager to use.
#
# It always exits 125 (unsupported action called).
#
exit 125
