#!/bin/bash

#
# util/bundle - Bundle Clockwork for VM Testing
#
# author:  James Hunt <james@jameshunt.us>
# created: 2011-10-04
#
# This little helper script creates a bundled
# Clockwork installation inside of a tarball.
#
# For most, this script is worthless.  I use it
# to ease the distribution of Clockwork to my
# virtual testbed network for real-world testing.
#
# YMMV
#

set -e

ROOT="/tmp/clockwork-bundle.$$/clockwork"
trap "sudo rm -rf $ROOT" INT TERM EXIT

echo "Building Clockwork"
echo " (in $ROOT)"
mkdir -p $ROOT
./configure --destdir $ROOT
make
sudo make install

echo
echo "Creating setup script"
cat > $ROOT/setup <<EOF
#!/bin/bash

echo "Setting up Clockwork from Bundle"
getent group  clockwork >/dev/null || groupadd -r clockwork
getent passwd clockwork >/dev/null || useradd -Mr -c "Clockwork" -g clockwork -d /var/clockwork clockwork

echo -n " - user: "
getent passwd clockwork

echo -n " - group: "
getent group clockwork
chown -R clockwork:clockwork var etc sbin

echo
echo "Setup complete"
EOF
sudo chown root:root $ROOT/setup
sudo chmod 0755 $ROOT/setup

echo
echo "Pulling in libgear"
mkdir -p $ROOT/lib
cp /usr/lib/libgear.so* $ROOT/lib/
sudo mkdir -p $ROOT/usr/include
sudo cp /usr/include/gear.h $ROOT/usr/include

echo
echo "Final Bundle Directory"
sudo tree $ROOT/

echo
echo "Creating tar.gz bundle file"
sudo tar -C $ROOT/.. -czf bundle.tar.gz clockwork
