#!/bin/bash

#set -xe
set -e

CLIENT=$1
ROOT=$PWD/certs

if [ "$CLIENT" = "" ]; then
	echo "USAGE: $0 client.fqdn"
	exit 1
fi

if [ -f $CLIENT ]; then
	CERT=$CLIENT;
else
	CERT=$ROOT/CA/certs/$CLIENT.pem
fi

if [ ! -f $CERT ]; then
	echo "$CERT: no such certificate"
	exit 1
fi

echo "$CERT:"
openssl x509 -in $CERT -noout -text
