#!/bin/bash

set -xe

CLIENT=$1
ROOT=$PWD/certs

if [ "$CLIENT" = "" ]; then
	echo "USAGE: $0 client.fqdn"
	exit 1
fi

if [ ! -d "$ROOT/$CLIENT" ]; then
	echo "$ROOT/$CLIENT does not exist..."
	echo "Looks like $CLIENT has not issued a signing request!"
	exit 1
fi

serial=$(cat $ROOT/CA/serial)

OPENSSL_CONF=$ROOT/CA/openssl.conf \
	openssl ca -in $ROOT/$CLIENT/request.pem

cd $ROOT/CA/certs
ln -s $serial.pem $CLIENT.pem

