Document: clockwork
Title: Debian clockwork Manual
Author: <insert document author here>
Abstract: This manual describes what clockwork is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/clockwork/clockwork.sgml.gz

Format: postscript
Files: /usr/share/doc/clockwork/clockwork.ps.gz

Format: text
Files: /usr/share/doc/clockwork/clockwork.text.gz

Format: HTML
Index: /usr/share/doc/clockwork/html/index.html
Files: /usr/share/doc/clockwork/html/*.html
