#!/bin/sh -e

#
# clockwork-agent postinst
#
# author:  James Hunt <james@niftylogic.com>
# created: 2014-07-07
#

CWKEY=/bin/cwkey
CERTS=/etc/clockwork/certs
LOCKDIR=/var/lock/cogd

create_dir() {
	dir="$1"
	name="$2"

	if [ ! -d $dir ]; then
		echo "Creating $name $dir"
		mkdir -p $dir
	fi
}

create_key() {
	file="$1"
	name="$2"

	if ! test -f "$file" && ! test -f "$file.pub"; then
		echo "Creating $name $file"
		$CWKEY -f $file
	fi
}

case "$1" in
configure)
	create_dir $LOCKDIR '' '' "lock directory"

	if [ -x $CWKEY ]; then
		create_dir $CERTS      "certificate store"
		create_key $CERTS/cogd "cogd certificate"
	fi

	if [ -z "$COGD" ]; then
		# not running under cogd, it's okay to restart
		rm -f $LOCKDIR/.needs-restart

		if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
			invoke-rc.d cogd restart || exit $?
		else
			/etc/init.d/cogd restart || exit $?
		fi
	else
		# running under a cogd CFM run; don't restart
		# out from under ourselves!
		touch $LOCKDIR/.needs-restart
	fi

	;;
*)
	exit 0
	;;
esac

#DEBHELPER#

exit 0
