extras/vim/ftdetect/clockwork.vim       usr/share/vim/addons/ftdetect
extras/vim/registry/vim-clockwork.yaml  usr/share/vim/registry
extras/vim/syntax/clockd.vim            usr/share/vim/addons/syntax
extras/vim/syntax/clockwork.vim         usr/share/vim/addons/syntax
extras/vim/syntax/cogd.vim              usr/share/vim/addons/syntax
extras/vim/syntax/cwrc.vim              usr/share/vim/addons/syntax
extras/vim/syntax/meshd.vim             usr/share/vim/addons/syntax
extras/vim/syntax/pnasm.vim             usr/share/vim/addons/syntax
