#!/bin/bash

#
# ext/build-openssl - Build PURIFY'd version of OpenSSL
#
# Usage: ext/build-openssl 0.9.8k /path/to/ext/dir
#
# This local version of OpenSSL is compiled with insecure settings
# that are ideal for predictability from a memory checking standpoint.
# Basically, unless OpnSSL is compiled with -DPURIFY, valgrind will
# complain about uninitialized memory and tons of memory leaks
# that don't really exist.
#

V=$1
ROOT=$2

echo
echo "Building OpenSSL v$V in $ROOT"
echo "------------------------------------------------"

set -ex

rm -rf $ROOT/openssl
rm -rf $ROOT/build/openssl-$V
mkdir $ROOT/openssl
tar -C $ROOT/build -xzf $ROOT/openssl-$V.tar.gz
(cd $ROOT/build/openssl-$V
 ./config --prefix=$ROOT/openssl shared -DPURIFY
 make
 make install)
rm -rf $ROOT/build/openssl-$V
