#!/bin/bash

echo "safeguard in effect.  edit t/setup to remove"
exit 0

mkdir -p t/data/x509/{keys,csrs,certs,ca}
touch t/data/x509/ca/index.txt
echo "123455" > t/data/x509/ca/serial

export OPENSSL_CONF=t/data/x509/ca.conf
openssl req -x509 -newkey rsa:2048 -nodes -days 3650 \
	-outform PEM -out t/data/x509/ca/cert.pem &>/dev/null
unset OPENSSL_CONF

openssl genrsa -passout pass: -out t/data/x509/keys/rsa128.pem   128 &>/dev/null
openssl genrsa -passout pass: -out t/data/x509/keys/rsa1024.pem 1024 &>/dev/null
openssl genrsa -passout pass: -out t/data/x509/keys/rsa2048.pem 2048 &>/dev/null
openssl genrsa -passout pass: -out t/data/x509/keys/test.pem    2048 &>/dev/null

# Generating a test Certificate Signing Request
openssl req -new -nodes \
	-subj "/C=US/ST=New York/L=Buffalo/O=NiftyLogic/OU=R&D/OU=CWA/CN=csr.niftylogic.net" \
	-key t/data/x509/keys/test.pem -out t/data/x509/csrs/csr.pem &>/dev/null

openssl req -new -nodes \
	-subj "/C=US/ST=New York/L=Buffalo/O=Signing Test/OU=R&D/OU=CWA/CN=sign.niftylogic.net" \
	-key t/data/x509/keys/test.pem -out t/data/x509/csrs/sign-me.pem &>/dev/null

openssl req -new -nodes \
	-subj "/C=US/ST=New York/L=Buffalo/O=NiftyLogic/OU=R&D/OU=CWA/CN=signed.niftylogic.net" \
	-key t/data/x509/keys/test.pem -out t/data/x509/csrs/test.pem &>/dev/null

# Generating a test Certificate (signed)
openssl x509 -req -days 365 \
	-outform PEM -out t/data/x509/certs/test.pem \
	-inform  PEM -in  t/data/x509/csrs/test.pem \
	-CA t/data/x509/ca/cert.pem \
	-CAkey t/data/x509/ca/key.pem \
	-CAserial t/data/x509/ca/serial &>/dev/null

# Generating a test Certificate (signed) for revocation tests
openssl req -new -nodes \
	-subj "/C=US/ST=New York/L=Buffalo/O=NiftyLogic/OU=R&D/OU=CWA/CN=REVOKE.rd.niftylogic.net" \
	-key t/data/x509/keys/test.pem -out t/data/x509/csrs/revoke-me.pem &>/dev/null
openssl x509 -req -days 365 \
	-outform PEM -out t/data/x509/certs/revoke-me.pem \
	-inform  PEM -in  t/data/x509/csrs/revoke-me.pem \
	-CA t/data/x509/ca/cert.pem \
	-CAkey t/data/x509/ca/key.pem \
	-CAserial t/data/x509/ca/serial &>/dev/null

# print fingerprints
echo -n "test.pem: "
openssl x509 -noout -in t/data/x509/certs/test.pem -fingerprint | sed -e 's/.*=//' | dd conv=lcase 2>/dev/null
echo -n "revoke-me.pem: "
openssl x509 -noout -in t/data/x509/certs/revoke-me.pem -fingerprint | sed -e 's/.*=//' | dd conv=lcase 2>/dev/null
